"""Concrete adapters for the B.O.T.S. desktop application."""

from .process_execution import (
    BoundedProcessExecutor,
    ProcessExecutionRequest,
    ProcessExecutionResult,
    ProcessResourceLimits,
    ProcessReceipt,
    ProcessState,
    ResourceLimitExceeded,
    CodeExecutor,
    CodeExecutionRequest,
    bounded_workspace,
)

from .git_authority import (
    GitAuthorityManager,
    GitAuthorityLevel,
    GitOperationRequest,
    GitOperationResult,
    GitOperationState,
    GitAuthorityGrant,
    GitAuthorityBindingScope,
    GitReceipt,
    DisposableGitRepository,
    DisposableGitRemote,
    GitInspectAuthority,
    GitConsequentialAuthority,
    GitWorkspaceOwnership,
    disposable_git_repository,
    disposable_git_remote,
    git_workspace_isolation,
)

__all__ = [
    "BoundedProcessExecutor",
    "ProcessExecutionRequest",
    "ProcessExecutionResult",
    "ProcessResourceLimits",
    "ProcessReceipt",
    "ProcessState",
    "ResourceLimitExceeded",
    "CodeExecutor",
    "CodeExecutionRequest",
    "bounded_workspace",
    "GitAuthorityManager",
    "GitAuthorityLevel",
    "GitOperationRequest",
    "GitOperationResult",
    "GitOperationState",
    "GitAuthorityGrant",
    "GitAuthorityBindingScope",
    "GitReceipt",
    "DisposableGitRepository",
    "DisposableGitRemote",
    "GitInspectAuthority",
    "GitConsequentialAuthority",
    "GitWorkspaceOwnership",
    "disposable_git_repository",
    "disposable_git_remote",
    "git_workspace_isolation",
]
